theme: jekyll-theme-slate
title: Kvantum programozási nyelvek
description: Házi feladat a BMEVIHIAV06 tantárgyhoz; a kvantum programozás elméleti bemutatása, már elérhető nyelvek és módszerek áttekintése.
